name: Build WebDesk

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.75"

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: x86_64-pc-windows-msvc
          override: true
          profile: minimal

      - name: Install vcpkg dependencies
        run: |
          $ErrorActionPreference = "Stop"
          git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          .\bootstrap-vcpkg.bat
          $env:VCPKG_ROOT = "C:\vcpkg"
          .\vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static aom:x64-windows-static
        shell: pwsh

      - name: Build WebDesk
        run: |
          $env:VCPKG_ROOT = "C:\vcpkg"
          cargo build --release --target x86_64-pc-windows-msvc
        shell: pwsh

      - name: Rename executable
        run: |
          Copy-Item target\x86_64-pc-windows-msvc\release\rustdesk.exe WebDesk.exe
        shell: pwsh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebDesk-Windows-x64
          path: WebDesk.exe
